version: '3'

vars:
  NAME: go-import-server
  BUILD_TIME:
    sh: date -u '+%Y-%m-%d %I:%M:%S %Z'
  BUILD_COMMIT:
    sh: git rev-parse HEAD

tasks:
  default:
    cmds:
      - task: web

  web:
    desc: Build the binary and start the web server
    deps: [build]
    cmds:
      - ./{{.NAME}}

  build:
    desc: Build binary
    cmds:
      - go build -v -trimpath -o {{.NAME}}
    sources:
      - ./*.go

  release:
    desc: Build the binary and pack resources to ZIP files
    cmds:
      - env GOOS=darwin GOARCH=amd64 go build -ldflags '-X main.Version={{.BUILD_COMMIT}}' -o {{.NAME}}; tar czf {{.NAME}}_darwin_amd64.tar.gz {{.NAME}}
      - env GOOS=linux GOARCH=amd64 go build -ldflags '-X main.Version={{.BUILD_COMMIT}}' -o {{.NAME}}; tar czf {{.NAME}}_linux_amd64.tar.gz {{.NAME}}
      - env GOOS=windows GOARCH=amd64 go build -ldflags '-X main.Version={{.BUILD_COMMIT}}' -o {{.NAME}}; tar czf {{.NAME}}_windows_amd64.tar.gz {{.NAME}}

  clean:
     desc: Clean up meta and packed files
     cmds:
       - go clean
       - rm -f *.tar.gz
